[dock]
background_opacity = 1.0

[notification]
background_opacity = 1.0

[osd]
background_opacity = 1.0

[shell]
font_family = "Comfortaa"

[theme]
custom_palette = "stylix"
mode = "dark"
source = "custom"
